### ISSUE TITLE
make all fails due to tensorflow

### ISSUE THREAD

**Issue by wlbocr** [OCR-D/ocrd_all#219] opened 2020-11-18 09:29 UTC
I am trying to install OCR-D Software. The installation fails during the "make all"-step because tensorflow is not compatible with python 3.8. :
_ERROR: Could not find a version that satisfies the requirement tensorflow-gpu==1.15.* (from ocrd-cor-asv-ann==0.1.6) (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.2.1, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2, 2.3.0, 2.3.1, 2.4.0rc0, 2.4.0rc1)
ERROR: No matching distribution found for tensorflow-gpu==1.15.* (from ocrd-cor-asv-ann==0.1.6)_

Python version will be updated on the step before "sudo make deps-ubuntu": 
_python3 is already the newest version (3.8.2-0ubuntu2)._

How to fix this problem?

**Comment by kba** [comment] 2020-11-18 09:50
tensorflow does not provide packages of tensorflow < 2.3 for Python 3.8. That is why we're recommending deployment on Ubuntu 18.04 because Python is still at 3.7 for which packages are available of all relevant tensorflow versions.

So, I recommend either downgrading Python, downgrading Ubuntu from 20.04 to 18.04 or using the docker deployment option.

See the [wiki article on Ubuntu installation](https://github.com/OCR-D/ocrd-website/wiki/OCR-D-on-Debian-and-Ubuntu) for a recipe to downgrade Python.

**Comment by wlbocr** [comment] 2020-11-18 10:03
OCD-D installation via Docker gives the following error message:

sudo snap install docker
docker pull ocrd/all:maximum
Got permission denied while trying to connect to the Docker daemon socket at uni 
x:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.40/images/cr                          eate?fromImage=ocrd%2Fall&tag=maximum: dial unix /var/run/docker.sock: connect:                           
permission denied

**Comment by kba** [comment] 2020-11-18 10:05
> OCD-D installation via Docker gives the following error message:
> 
> sudo snap install docker
> docker pull ocrd/all:maximum
> Got permission denied while trying to connect to the Docker daemon socket at uni
> x:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.40/images/cr eate?fromImage=ocrd%2Fall&tag=maximum: dial unix /var/run/docker.sock: connect:
> permission denied

Are you in the `docker` group? `sudo usermod -a -G docker YOURUSERNAME`, log out/log in and try again? If you need more support debugging, feel free to drop by the [chat](https://gitter.im/OCR-D/Lobby).

**Comment by kba** [comment] 2020-12-02 09:57
Did you manage to solve this @wlbocr?

**Comment by wlbocr** [comment] 2020-12-02 10:17
The docker installation actually worked so far. The installation is not yet complete. On the last step I got the massage: 
_open /var/snap/docker/common/var-lib-docker/tmp/GetImageBlob642383193: no such file or directory_

**Comment by bertsky** [comment] 2020-12-28 21:41
This looks like the snap method did not install Docker properly. I have no experience with snap. The recommended way for Docker installation on Ubuntu is [via 3rd-party apt source](https://docs.docker.com/engine/install/ubuntu/).

**Comment by kba** [comment] 2020-12-29 10:43
> The docker installation actually worked so far. The installation is not yet complete. On the last step I got the massage:
> _open /var/snap/docker/common/var-lib-docker/tmp/GetImageBlob642383193: no such file or directory_

Does the problem persist after a reboot or [`sudo systemctl restart docker`](https://github.com/moby/moby/issues/22074#issuecomment-224921134)?

**Comment by Aysoltan** [comment] 2021-03-24 17:30
I tryed different ways to solve the problem and only one helped: the new installation of Ubuntu Bionic 18.04 (LTS) -> manualy installation ocr-d

**Comment by stweil** [comment] 2021-03-24 18:24
@Aysoltan, a [manual installation of Python 3.7](https://github.com/OCR-D/ocrd-website/wiki/OCR-D-on-Debian-and-Ubuntu#installation-of-python-37) would also help. You can then build OCR-D using Python 3.7 for which the required versions of Tensorflow exist.

**Comment by bertsky** [comment] 2021-06-16 20:50
Duplicate of #235 (but discussions are complementary so far).

**Closed** 2022-03-18 14:35 UTC
