### ISSUE TITLE
Many OCR-D processors are not executable 

### ISSUE THREAD

**Issue by hnesk** [OCR-D/ocrd_all#150] opened 2020-08-15 23:07 UTC
After checkout of current master 18547e47c58b4b39835a8450c7cae21a0f4f377f and `make modules` / `make all` my venv/bin directory looks like this:

```
(venv) jk@jk-XPS-13:~/Projekte/ocrd_all_2020$ ll venv/bin/ocrd*
-rwxrwxr-x 1 jk jk   237 Aug 14 20:03 venv/bin/ocrd*
-rw-rw-r-- 1 jk jk   196 Aug 15 11:48 venv/bin/ocrd-anybaseocr-binarize
-rw-rw-r-- 1 jk jk   206 Aug 15 11:48 venv/bin/ocrd-anybaseocr-block-segmentation
-rw-rw-r-- 1 jk jk   192 Aug 15 11:48 venv/bin/ocrd-anybaseocr-crop
-rw-rw-r-- 1 jk jk   194 Aug 15 11:48 venv/bin/ocrd-anybaseocr-deskew
-rw-rw-r-- 1 jk jk   194 Aug 15 11:48 venv/bin/ocrd-anybaseocr-dewarp
-rw-rw-r-- 1 jk jk   203 Aug 15 11:48 venv/bin/ocrd-anybaseocr-layout-analysis
-rw-rw-r-- 1 jk jk   196 Aug 15 11:48 venv/bin/ocrd-anybaseocr-textline
-rw-rw-r-- 1 jk jk   193 Aug 15 11:48 venv/bin/ocrd-anybaseocr-tiseg
-rw-rw-r-- 1 jk jk   193 Aug 14 20:19 venv/bin/ocrd-calamari-recognize
-rwxrwxr-x 1 jk jk   986 Aug 15 23:26 venv/bin/ocrd-cis-align*
-rwxrwxr-x 1 jk jk   984 Aug 15 23:26 venv/bin/ocrd-cis-data*
-rwxrwxr-x 1 jk jk  1006 Aug 15 23:26 venv/bin/ocrd-cis-ocropy-binarize*
-rwxrwxr-x 1 jk jk   998 Aug 15 23:26 venv/bin/ocrd-cis-ocropy-clip*
-rwxrwxr-x 1 jk jk  1004 Aug 15 23:26 venv/bin/ocrd-cis-ocropy-denoise*
-rwxrwxr-x 1 jk jk  1002 Aug 15 23:26 venv/bin/ocrd-cis-ocropy-deskew*
-rwxrwxr-x 1 jk jk  1002 Aug 15 23:26 venv/bin/ocrd-cis-ocropy-dewarp*
-rwxrwxr-x 1 jk jk   996 Aug 15 23:26 venv/bin/ocrd-cis-ocropy-rec*
-rwxrwxr-x 1 jk jk  1008 Aug 15 23:26 venv/bin/ocrd-cis-ocropy-recognize*
-rwxrwxr-x 1 jk jk  1008 Aug 15 23:26 venv/bin/ocrd-cis-ocropy-resegment*
-rwxrwxr-x 1 jk jk  1004 Aug 15 23:26 venv/bin/ocrd-cis-ocropy-segment*
-rwxrwxr-x 1 jk jk  1000 Aug 15 23:26 venv/bin/ocrd-cis-ocropy-train*
-rwxrwxr-x 1 jk jk   998 Aug 15 23:26 venv/bin/ocrd-cis-postcorrect*
-rw-rw-r-- 1 jk jk   195 Aug 14 16:28 venv/bin/ocrd-cor-asv-ann-evaluate
-rw-rw-r-- 1 jk jk   194 Aug 14 16:28 venv/bin/ocrd-cor-asv-ann-process
-rwxrwxr-x 1 jk jk  1004 Aug 14 20:15 venv/bin/ocrd-dinglehopper*
-rwxrwxr-x 1 jk jk   267 Aug 14 20:03 venv/bin/ocrd-dummy*
-rwxrwxr-x 1 jk jk  6494 Aug 15 23:03 venv/bin/ocrd-export-larex*
-rwxrwxr-x 1 jk jk  2879 Aug 15 23:26 venv/bin/ocrd-fileformat-transform*
-rwxrwxr-x 1 jk jk  2976 Aug 14 19:51 venv/bin/ocrd-im6convert*
-rwxrwxr-x 1 jk jk  6285 Aug 15 23:03 venv/bin/ocrd-import*
-rw-rw-r-- 1 jk jk   187 Aug 14 17:25 venv/bin/ocrd-keraslm-rate
-rwxrwxr-x 1 jk jk  1690 Aug 15 23:03 venv/bin/ocrd-make*
-rwxrwxr-x 1 jk jk 17455 Aug 14 20:15 venv/bin/ocrd-olena-binarize*
-rwxrwxr-x 1 jk jk  5281 Aug 14 20:19 venv/bin/ocrd-pagetopdf*
-rw-rw-r-- 1 jk jk   192 Aug 15 02:43 venv/bin/ocrd-pc-segmentation
-rwxrwxr-x 1 jk jk  1003 Aug 14 20:00 venv/bin/ocrd-preprocess-image*
-rwxrwxr-x 1 jk jk  1069 Aug 15 23:03 venv/bin/ocrd-repair-inconsistencies*
-rw-rw-r-- 1 jk jk   196 Aug 15 12:22 venv/bin/ocrd-sbb-textline-detector
-rwxrwxr-x 1 jk jk   191 Aug 15 02:43 venv/bin/ocrd-segment-evaluate*
-rwxrwxr-x 1 jk jk   196 Aug 15 02:43 venv/bin/ocrd-segment-extract-lines*
-rwxrwxr-x 1 jk jk   196 Aug 15 02:43 venv/bin/ocrd-segment-extract-pages*
-rwxrwxr-x 1 jk jk   198 Aug 15 02:43 venv/bin/ocrd-segment-extract-regions*
-rwxrwxr-x 1 jk jk   192 Aug 15 02:43 venv/bin/ocrd-segment-from-coco*
-rwxrwxr-x 1 jk jk   193 Aug 15 02:43 venv/bin/ocrd-segment-from-masks*
-rwxrwxr-x 1 jk jk   189 Aug 15 02:43 venv/bin/ocrd-segment-repair*
-rwxrwxr-x 1 jk jk   199 Aug 15 02:43 venv/bin/ocrd-segment-replace-original*
-rwxrwxr-x 1 jk jk  1003 Aug 14 20:00 venv/bin/ocrd-skimage-binarize*
-rwxrwxr-x 1 jk jk  1001 Aug 14 20:00 venv/bin/ocrd-skimage-denoise*
-rwxrwxr-x 1 jk jk  1009 Aug 14 20:00 venv/bin/ocrd-skimage-denoise-raw*
-rwxrwxr-x 1 jk jk  1005 Aug 14 20:00 venv/bin/ocrd-skimage-normalize*
-rwxrwxr-x 1 jk jk  1022 Aug 14 20:18 venv/bin/ocrd-tesserocr-binarize*
-rwxrwxr-x 1 jk jk  1014 Aug 14 20:18 venv/bin/ocrd-tesserocr-crop*
-rwxrwxr-x 1 jk jk  1018 Aug 14 20:18 venv/bin/ocrd-tesserocr-deskew*
-rwxrwxr-x 1 jk jk  1024 Aug 14 20:18 venv/bin/ocrd-tesserocr-recognize*
-rwxrwxr-x 1 jk jk  1030 Aug 14 20:18 venv/bin/ocrd-tesserocr-segment-line*
-rwxrwxr-x 1 jk jk  1034 Aug 14 20:18 venv/bin/ocrd-tesserocr-segment-region*
-rwxrwxr-x 1 jk jk  1032 Aug 14 20:18 venv/bin/ocrd-tesserocr-segment-table*
-rwxrwxr-x 1 jk jk  1030 Aug 14 20:18 venv/bin/ocrd-tesserocr-segment-word*
-rw-rw-r-- 1 jk jk   204 Aug 15 12:21 venv/bin/ocrd-typegroups-classifier
```
I had several errors during `make all`, but as far as I remember these were all due to a bad internet connection.

**Comment by stweil** [comment] 2020-08-16 10:08
I expect even some more files with missing execute attribute: `cor*` and `keraslm-rate`. All those executables are now in `venv/local/sub-venv/*/bin/`, and the entries in `venv/bin` are only generated scripts (therefore rather small). The execute attribute is normally set using `chmod +x`, so the question is why did that not work for you?

**Comment by stweil** [comment] 2020-08-16 10:10
Do you also have `venv/bin/page2img`, and does it have correct attributes?

**Comment by kba** [comment] 2020-08-16 10:39
>> The execute attribute is normally set using chmod +x. So the question is why did that not work for you?

I strongly suspect because

> I had several errors during make all, but as far as I remember these were all due to a bad internet connection.

Before debugging further, it would help to make sure that is not the problem:

```
find venv/bin -name 'ocrd-*' \! -executable -delete
make all
```

**Comment by stweil** [comment] 2020-08-16 10:53
No matter what went wrong, the build should either create files with the right attributes, or abort without any such file at all.

@hnesk, do you have a build protocol of the original build? I suggest to always build with a build protocol, for example using `nohup make all | tee build.log`.

**Comment by kba** [comment] 2020-08-16 11:00
:+1: for `make all | tee build.log`

I ran into this problem while we fine-tuned https://github.com/OCR-D/ocrd_all/pull/118 as well, with non-executable executables. With a log we could identify the sequence of events that lead to such an inacceptable inconsistent state.

**Comment by bertsky** [comment] 2020-08-16 13:50
> and the entries in `venv/bin` are only generated scripts (therefore rather small). The execute attribute is normally set using `chmod +x`.

Exactly. And since this affects executables from multiple modules, I cannot image how this could have happened without error message, interrupting the overall build.

@hnesk Did you run with `-k` or run multiple times by any chance?

> No matter what went wrong, the build should either create files with the right attributes, or abort without any such file at all.

Hard to tell what exactly went wrong, but we could at least declare these targets as invalid (and delete them) if any error happened by adding `.DELETE_ON_ERROR:` anywhere in the Makefile.

**Comment by kba** [comment] 2020-08-16 14:05
> we could at least declare these targets as invalid (and delete them) if any error happened by adding .DELETE_ON_ERROR: anywhere in the Makefile.

:+1:

**Comment by bertsky** [comment] 2020-08-17 08:08
> > we could at least declare these targets as invalid (and delete them) if any error happened by adding .DELETE_ON_ERROR: anywhere in the Makefile.
> 
> +1

https://github.com/OCR-D/ocrd_all/pull/145/commits/13d8da456be4bb1f581577d626b75fd385ee3207

**Comment by hnesk** [comment] 2020-08-17 10:17
I actually ran `make all` several times, because often the installation of bigger packages failed (tensorflow, keras, ...) due to my bad internet connection.  
Nearly all of the processors work for me now, except ocrd_typegroups_classifier

I have only a [build.log](https://github.com/OCR-D/ocrd_all/files/5083604/build.log) of the last attempt (trying to install ocrd_typegroups_classifier), made with `make all 2>&1 | tee build.log`, and I suppose that's another problem. 

About the original problem, I will try another fresh install now with logging and see how it works. 
That .DELETE_ON_ERROR helps seems plausible

**Comment by kba** [comment] 2020-08-17 12:12
> I have only a [build.log](https://github.com/OCR-D/ocrd_all/files/5083604/build.log) of the last attempt (trying to install ocrd_typegroups_classifier), made with `make all 2>&1 | tee build.log`, and I suppose that's another problem.

> `ERROR: Directory '.' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.`

This looks like ocrd_typegroups_classifier submodule was not checked out, hence the directory is empty and the process aborts. @cneud reported the same issue this morning (c.f. #151).

**Comment by hnesk** [comment] 2020-08-17 12:17
It worked with a fresh install now, sorry about all the fuzz. I suppose it had to do to with pip timeout errors, but now that my cache is seeded, it went flawlessly.

**Comment by hnesk** [comment] 2020-08-17 12:21
> This looks like ocrd_typegroups_classifier submodule was not checked out, hence the directory is empty and the process aborts. @cneud reported the same issue this morning (c.f. #151).

Yes, some submodule folders were empty, and I had to apply `make deinit` and `make modules` again

**Comment by stweil** [comment] 2020-08-17 18:11
Issue #152 describes are reproducible way how to get "processors" which are no executable.

**Comment by stweil** [comment] 2020-08-18 07:17
Hopefully the problem described in this issue is fixed in the latest code (commit ca242633a41730d7ce9c2a8f1c8206c94049e55b).

**Comment by stweil** [comment] 2020-08-18 07:19
> Agreed. Hard to tell what exactly went wrong, but we could at least declare these targets as invalid (and delete them) if any error happened by adding `.DELETE_ON_ERROR:` anywhere in the Makefile.

Adding a template script for each sub-venv to git would be my favourite solution. Such a script can be either linked (yes, I know your objection) or copied, nothing which can go wrong. That would also simplify the Makefile.

**Comment by bertsky** [comment] 2020-08-18 09:23
> Adding a template script for each sub-venv to git would be my favourite solution. Such a script can be either linked (yes, I know your objection) or copied, nothing which can go wrong. That would also simplify the Makefile.

For one, that is unrelated to this issue and the `.DELETE_ON_ERROR` problem.

Second, I don't see how you want to make a static template for a dynamic problem: You need to replace the venv path, the delegated executable path and the delegating executable name. Even if you find a solution to replace them in your template, this would not simplify the Makefile.

**Comment by stweil** [comment] 2020-08-18 09:33
Copying an executable template either creates an executable file or none at all, so it would have solved this issue.

And a template for a given sub-venv can calculate its `VIRTUAL_ENV` from the known `VIRTUAL_ENV` or the parent venv. The delegated executable name and the delegating executable name have known directories and identical basenames, so that is also easy to realize.

**Comment by bertsky** [comment] 2020-08-18 10:04
> Copying an executable template either creates an executable file or none at all, so it would have solved this issue.

Oh, right.

> And a template for a given sub-venv can calculate its `VIRTUAL_ENV` from the known `VIRTUAL_ENV` of the parent venv.

True again.

> The delegated executable name and the delegating executable name have known directories and identical basenames, so that is also easy to realize.

I am open to concrete suggestions (maybe I'm just too unimaginative).

**Closed** 2020-08-20 10:31 UTC
Labels: bug
